version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ${DOCKER_COMPOSE__SERVICES_PATH}/app/Dockerfile
        command: sh -c "composer install && php artisan migrate --seed"
        container_name: ${DOCKER_COMPOSE__CONTAINERS_BASE_NAME}-app
        networks:
            - ${DOCKER_COMPOSE__NETWORK_BASE_NAME}
        restart: on-failure
        volumes:
            - .:/app
        working_dir: /app
    db:
        container_name: ${DOCKER_COMPOSE__CONTAINERS_BASE_NAME}-db
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        image: mysql:5.7
        networks:
            - ${DOCKER_COMPOSE__NETWORK_BASE_NAME}
        restart: always
        volumes:
            - ./db:/var/lib/mysql
    nginx:
        container_name: ${DOCKER_COMPOSE__CONTAINERS_BASE_NAME}-nginx
        depends_on:
            - php-fpm
            - db
        image: nginx:1.23.1
        networks:
            - ${DOCKER_COMPOSE__NETWORK_BASE_NAME}
        ports:
            - 8000:80
        restart: always
        volumes:
            - ./:/var/www
            - ./storage/app/public:/var/www/public/storage
            - ${DOCKER_COMPOSE__SERVICES_PATH}/nginx:/etc/nginx/conf.d
        working_dir: /var/www
    php-fpm:
        build:
            args:
                user: oleg
                uid: 1000
            context: .
            dockerfile: ${DOCKER_COMPOSE__SERVICES_PATH}/fpm/Dockerfile
        container_name: ${DOCKER_COMPOSE__CONTAINERS_BASE_NAME}-fpm
        depends_on:
            - db
        image: php:8.0-fpm
        networks:
            - ${DOCKER_COMPOSE__NETWORK_BASE_NAME}
        restart: always
        volumes:
            - ./:/var/www
        working_dir: /var/www
    phpmyadmin:
        container_name: ${DOCKER_COMPOSE__CONTAINERS_BASE_NAME}-phpmyadmin
        depends_on:
            - db
        environment:
            - PMA_HOST=${DB_HOST}
            - PMA_PORT=${DB_PORT}
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
        image: phpmyadmin
        networks:
            - ${DOCKER_COMPOSE__NETWORK_BASE_NAME}
        ports:
            - 8001:80
        restart: always
networks:
    laravel-docker-NMP-network:
        driver: bridge
