version: '3.8'

services:
    app:
        build:
            args:
                user: oleg
                uid: 1000
            context: ./
            dockerfile: ./docker-compose/services/app/Dockerfile
        image: laravel-sales
        depends_on:
            - db
        container_name: laravel-sales-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - laravel-sales-network
    db:
        image: mysql:5.7
        container_name: laravel-sales-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - laravel-sales-network
    phpmyadmin:
        image: phpmyadmin
        depends_on:
            - db
        restart: always
        ports:
            - 8001:80
        environment:
            - PMA_HOST=${DB_HOST}
            - PMA_PORT=${DB_PORT}
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
        networks:
            - laravel-sales-network
    nginx:
        image: nginx:1.17-alpine
        depends_on:
            - app
        container_name: laravel-sales-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/services/nginx:/etc/nginx/conf.d
        networks:
            - laravel-sales-network

networks:
    laravel-sales-network:
        driver: bridge
